import {gql} from '@apollo/client';
import {IUser} from '@/types/user';

export interface IUserMeResponse {
  me: IUser;
}

export const USER_ME_QUERY = gql`
  query me {
    me {
      id
      fullName
      phone
      email
      avatar {
        path
        fileName
        width
        height
        size
        isOriginal
      }
      isResident
      birthDate
      autoGenerated
      Country {
        id
        name
        code
      }
      City {
        id
        name
      }
      Timezone {
        label
        name
        tzCode
        utc
      }
      Sale {
        id
        name
        title
        active
      }
      Currency {
        id
        name
        code
      }
      Language {
        id
        name
        nativeName
        code
        index
      }
      Role {
        id
        name
        displayName
      }
      Subscription {
        maxActivated
        activationsLeft
        activationsUsed
        
        Plan {
          id
          shortTitle
          productId
        }
      }
    }
  }
`;

export const ME_SWR = `
query me {
  me {
    id
    fullName
    phone
    email
    avatar {
      path
      fileName
      width
      height
      size
      isOriginal
    }
    isResident
    birthDate
    autoGenerated
    Country {
      id
      name
      code
    }
    City {
      id
      name
    }
    Timezone {
      label
      name
      tzCode
      utc
    }
    Sale {
      id
      name
      title
      active
    }
    Currency {
      id
      name
      code
    }
    Language {
      id
      name
      nativeName
      code
      index
    }
    Role {
      id
      name
      displayName
    }
  }
}
`;
