export const AVATAR_THEME = {
  MESSAGE_AVATAR_THEME_DEFAULT: 'Куратор',
  MESSAGE_AVATAR_THEME_VIP: 'VIP',
  MESSAGE_AVATAR_THEME_VIP_PLUS: 'VIP+',
};

export const AVATAR_REGALIA = {
  MESSAGE_THEME_CURATOR: 'Куратор',
  MESSAGE_THEME_ORDINARY: '',
  MESSAGE_AVATAR_THEME_DEFAULT: '',
  MESSAGE_AVATAR_THEME_VIP: 'VIP',
  MESSAGE_AVATAR_THEME_VIP_PLUS: 'VIP+',
  MESSAGE_THEME_VIP: 'VIP'
};

export const CHAT_TYPES = {
  ENTITY_NAME_APPOINTMENT: 'appointment-chat',
  ENTITY_NAME_AUDIO: 'aidio-chat',
  ENTITY_NAME_AUDIO_MARK: 'audio-mark-chat',
  ENTITY_NAME_AUTHOR: 'author-chat',
  ENTITY_NAME_BANNER: 'banner-chat',
  ENTITY_NAME_CATEGORY: 'category-chat',
  ENTITY_NAME_CMS_DEPARTMENT: 'cms-department-chat',
  ENTITY_NAME_CMS_ROLE: 'cms-role-chat',
  ENTITY_NAME_CMS_USER: 'cms-user-chat',
  ENTITY_NAME_CONSULTATION: 'consultation-chat',
  ENTITY_NAME_CONSULTATION_CONTENT: 'consultation-content-chat',
  ENTITY_NAME_CONSULTATION_FEEDBACK: 'consultation-feedback-chat',
  ENTITY_NAME_COUPON: 'consultation-coupon-chat',
  ENTITY_NAME_COURSE: 'course-chat',
  ENTITY_NAME_COURSE_CONTENT: 'course-content-chat',
  ENTITY_NAME_COURSE_END_CONTENT: 'course-end-content-chat',
  ENTITY_NAME_COURSE_FEEDBACK: 'course-feedback-chat',
  ENTITY_NAME_COURSE_TYPE: 'course-type-chat',
  ENTITY_NAME_CURRENCY: 'currency-chat',
  ENTITY_NAME_DEPARTMENT: 'department-chat',
  ENTITY_NAME_DOCUMENT: 'document-chat',
  ENTITY_NAME_DOCUMENT_CONTENT: 'document-content-chat',
  ENTITY_NAME_FAQ: 'faq-chat',
  ENTITY_NAME_FAQ_OPTION: 'faq-option-chat',
  ENTITY_NAME_FAVORITE: 'favorite-chat',
  ENTITY_NAME_FILE: 'file-chat',
  ENTITY_NAME_GIFT: 'gift-chat',
  ENTITY_NAME_GIFT_CONTENT: 'gift-content-chat',
  ENTITY_NAME_HOMEWORK: 'homework-chat',
  ENTITY_NAME_HOMEWORK_CONTENT: 'homework-content-chat',
  ENTITY_NAME_HOMEWORK_FLUENT_CONTENT: 'homework-fluent-content-chat',
  ENTITY_NAME_HOMEWORK_QUESTION_OPTION: 'homework-question-option-chat',
  ENTITY_NAME_HOMEWORK_RESULT: 'homework-result-chat',
  ENTITY_NAME_HOMEWORK_TASK: 'homework-task-chat',
  ENTITY_NAME_HOMEWORK_TEST_QUESTION: 'homework-test-question-chat',
  ENTITY_NAME_HOMEWORK_TEST_QUESTION_CONTENT:
    'homework-test-question-content-chat',
  ENTITY_NAME_HOMEWORK_TEST_QUESTION_OPTION:
    'homework-test-question-option-chat',
  ENTITY_NAME_IMAGE: 'image-chat',
  ENTITY_NAME_LANGUAGE: 'language-chat',
  ENTITY_NAME_LESSON: 'lesson-chat',
  ENTITY_NAME_LESSON_CONTENT: 'lesson-content-chat',
  ENTITY_NAME_MEETING_METHOD: 'meeting-method-chat',
  ENTITY_NAME_MERCHANT: 'merchant-chat',
  ENTITY_NAME_MESSAGE: 'message-chat',
  ENTITY_NAME_MODULE: 'module-chat',
  ENTITY_NAME_MODULE_CONTENT: 'module-content-chat',
  ENTITY_NAME_ORDER: 'order-chat',
  ENTITY_NAME_PAGE: 'page-chat',
  ENTITY_NAME_PAYMENT_METHOD: 'payment-method-chat',
  ENTITY_NAME_PAYMENT_SYSTEM: 'payment-system-chat',
  ENTITY_NAME_PLAN: 'plan-chat',
  ENTITY_NAME_PRICE_LIST: 'price-list-chat',
  ENTITY_NAME_PRICE_LIST_OPTION: 'price-list-option-chat',
  ENTITY_NAME_PRICE_LIST_PROPERTY: 'price-list-property-chat',
  ENTITY_NAME_PRODUCT: 'product-chat',
  ENTITY_NAME_PRODUCT_META: 'product-meta-chat',
  ENTITY_NAME_PROFILE: 'profile-chat',
  ENTITY_NAME_PURCHASE: 'purchase-chat',
  ENTITY_NAME_QUIZ: 'quiz-chat',
  ENTITY_NAME_QUIZ_CONTENT: 'quiz-content-chat',
  ENTITY_NAME_QUIZ_QUESTION: 'quiz-question-chat',
  ENTITY_NAME_QUIZ_QUESTION_CONTENT: 'quiz-question-content-chat',
  ENTITY_NAME_QUIZ_QUESTION_OPTION: 'quiz-question-option-chat',
  ENTITY_NAME_QUIZ_QUESTION_OPTION_QUIZ_QUESTION:
    'quiz-question-option-quiz-question-chat',
  ENTITY_NAME_SALE: 'sale-chat',
  ENTITY_NAME_SALE_CONTENT: 'sale-content-chat',
  ENTITY_NAME_SURVEY: 'survey-chat',
  ENTITY_NAME_SURVEY_OPTION: 'survey-option-chat',
  ENTITY_NAME_SURVEY_QUESTION: 'survey-question-chat',
  ENTITY_NAME_TAG: 'tag-chat',
  ENTITY_NAME_TERM: 'term-chat',
  ENTITY_NAME_THREAD: 'thread-chat',
  ENTITY_NAME_THREAD_CONTENT: 'thread-content-chat',
  ENTITY_NAME_TICKET: 'ticket-chat',
  ENTITY_NAME_TILDA_PAGE: 'tilda-page-chat',
  ENTITY_NAME_TILDA_PROJECT: 'tilda-project-chat',
  ENTITY_NAME_TRANSACTION: 'transaction-chat',
  ENTITY_NAME_USER: 'user-chat',
  ENTITY_NAME_USER_VIDEO_MARK: 'user-video-mark-chat',
  ENTITY_NAME_VIDEO: 'video-chat',
  ENTITY_NAME_VIDEO_MARK: 'video-mark-chat',
  ENTITY_NAME_VIDEO_SUBTITLE: 'video-subtitle-chat',
};
