export const CONSULTATION_DURATION: {[key: string]: string} = {
  CONSULTATION_DURATION_15M: '15 мин',
  CONSULTATION_DURATION_30M: '30 мин',
  CONSULTATION_DURATION_60M: '1 час',
};

export const CONSULTATION_DURATION_IN_SECONDS: {[key: string]: number} = {
  CONSULTATION_DURATION_15M: 900,
  CONSULTATION_DURATION_30M: 1800,
  CONSULTATION_DURATION_60M: 3600,
};
